# Generated by Django 5.0.1 on 2024-01-19 19:30

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='All_soil',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('soil_image', models.ImageField(null=True, upload_to='images/soil_image')),
                ('soil_name', models.CharField(max_length=100)),
                ('soil_discription', models.TextField(null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Crops',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('crops_image', models.ImageField(null=True, upload_to='images/tools_image')),
                ('crops_name', models.CharField(max_length=100)),
                ('crops_discription', models.TextField(null=True)),
                ('crops_use', models.TextField(null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Medicine',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('medicine_image', models.ImageField(null=True, upload_to='images/tools_image')),
                ('medicine_name', models.CharField(max_length=100)),
                ('medicine_discription', models.TextField(null=True)),
                ('medicine_use', models.TextField(null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Test_soil',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('soil_image', models.ImageField(null=True, upload_to='images/user_soil_image')),
                ('soil_discription', models.TextField(null=True)),
                ('soil_location', models.CharField(max_length=100)),
                ('soil_name_col', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Tools',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tools_image', models.ImageField(null=True, upload_to='images/tools_image')),
                ('tools_name', models.CharField(max_length=100)),
                ('tools_discription', models.TextField(null=True)),
                ('tools_use', models.TextField(null=True)),
            ],
        ),
    ]
