# Generated by Django 5.0.1 on 2024-01-20 19:31

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_soil', '0003_rename_user_test_soil_usersd'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Crops',
        ),
        migrations.DeleteModel(
            name='Medicine',
        ),
        migrations.DeleteModel(
            name='Tools',
        ),
        migrations.AddField(
            model_name='test_soil',
            name='date_added',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
